repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: check-json
        exclude: '^(package-lock\.json)'
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args: [
          --branch, main
        ]
      - id: trailing-whitespace
      - id: pretty-format-json
        exclude: '^(package-lock\.json)'
        args:
          - --autofix
