[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "language-golem-cli"
version = "0.1.0"
description = "A command-line language tutor using OpenAI's Realtime API"
readme = "README.md"
requires-python = ">=3.13"
license = "Apache-2.0"
authors = [
    { name = "Language Golem Contributors" },
]
classifiers = [
    "Environment :: Console",
    "Intended Audience :: Education",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Topic :: Education",
]
dependencies = [
    "openai>=1.0,<2.0",
]

[project.scripts]
language-golem = "langgolem.cli.main:main"

[tool.hatch.build]
packages = [
    "src/langgolem",
]
