# Copyright 2025 The Milton Hirsch Institute, B.V.
# SPDX-License-Identifier: Apache-2.0

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "language-golem-cli"
version = "0.1.0"
description = "A command-line language tutor using OpenAI's Realtime API"
readme = "README.md"
requires-python = ">=3.13"
license = "Apache-2.0"
authors = [
    { name = "Language Golem Contributors" },
]
classifiers = [
    "Environment :: Console",
    "Intended Audience :: Education",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Topic :: Education",
]
dependencies = [
    "certifi",
    "click>=8.0,<9.0",
    "openai-agents>=0.3,<1.0",
    "sounddevice>=0.5.2,<1.0",
    "tyminator>=1.0,<2.0",
    "websockets>=15.0,<16.0"
]

[project.scripts]
language-golem = "langgolem.cli.main:main"

[tool.uv]
dev-dependencies = [
    "fake-openai-agents",
    "fake-sounddevice",
]

[tool.hatch.build]
packages = [
    "src/langgolem",
]
